name: Build/release

on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Compile Electron App
        uses: x6Pnda/action-electron-compiler@v1.0.1
        with:
            # GitHub token, automatically provided to the action
            # (Optional)
            github_token: ${{ secrets.github_token }}

            # If the commit is tagged with a version (e.g. "v1.0.0"),
            # (Optional)
            release: ${{ startsWith(github.ref, 'refs/tags/v') }}

            # Package manager. NPM, PNPM and Yarn supported. Install Yarn and PNPM yourself. Default is NPM
            # (Optional)
            package_manager: PNPM

            # Skip buiding the application
            # (Optional)
            skip_build: false


