name: Build/release

on:
  push:
    tags: ["*"]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Publish Release with Electron Builder
        run: pnpm run build:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


